project:
  type: website
  output-dir: docs

website:
  title: "Jun Luu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3"            
      - text: "Labs"
        menu: 
          - href: labs/lab-01.qmd
            text: "Lab 1"
          - href: labs/lab-02.qmd
            text: "Lab 2"         
          - href: labs/lab-03.qmd
            text: "Lab 3"
          - href: labs/lab-04.qmd
            text: "Lab 4"
          - href: labs/lab-05.qmd
            text: "Lab 5"
            
format:
  html:
    theme: united
    toc: true
    code-fold: true

execute:
  freeze: auto
