project:
  type: website
  output-dir: docs

website:
  title: "Jun Luu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3"   
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4"    
          - href: weekly-notes/week-05-notes.qmd
            text: "Week 5" 
      - text: "Assignments"
        menu: 
          - href: assignments/assignment_1.qmd
            text: "Lab 1"
          - href: assignments/assignment_2/Luu_Jun_Assignment2.qmd
            text: "Lab 2"         
          - href: assignments/lab-03.qmd
            text: "Lab 3"
          - href: assignments/lab-04.qmd
            text: "Lab 4"
          - href: assignments/lab-05.qmd
            text: "Lab 5"
            
format:
  html:
    theme: united
    toc: true
    code-fold: true

execute:
  freeze: auto
