---
title: "About Me"
format: html
---

------------------------------------------------------------------------

My name is Jennifer Luu, but I go by Jun (pronounced like June)! I am discovering my path of blending my lived experience and background in construction engineering with urban spatial analytics.

I think the most effective way to tell you my story is by going through the cities I've lived and learned in. If you see a city you're thinking about visiting, let me know! I would love to share recommendations or even help you plan your trip!

# My Journey

*Leesburg, VA*

I grew up 1-1.5h outside of Washington D.C. It was in this politics-centered city where my flame of affordable housing ignited.

*Blacksburg, VA*

My interest in working in affordable housing led me to Virginia Tech, where I majored in Construction Engineering and Management. **GO HOKIES!**

*Chicago, IL*

I wanted to integrate myself into a city that with a strong history of housing reform and policy. It was here that I started to think about how my work in different construction projects were affecting the community that I was in. I began a personal research project in an attempt to quantify these effects.

*Los Angeles, CA*

During my time in LA, my research interests both expanded and deepened. I was able to see how housing directly affected healthcare and education.

*New York City, NY*

I had the amazing opportunity to work on my **dream** project- the thing that I had worked for all through undergrad: renovation of low-income housing in East Brooklyn. I could go on about this, but I will spare you the reading. (Feel free to reach out to me if you want to talk about it!)

*Philadelphia, PA*

It all led to right here, The University of Pennsylvania. Though I loved working in affordable housing construction and it felt like that was what I was running towards since I was 16, I realized something else that I wanted. It is extremely important to do the work in the field, but I wanted to do research to support future projects.

Thanks for reading! I hope you'll follow me to see where I go next! Maybe it'll be another city, but maybe I'll stay right here in Philly.
